### PR TITLE
🐛 Fix import of production build on Windows

### LINKED ISSUE #8: Importing the prod build fails on Windows
Ye olde Windows path issues, hooray!

Running the built/production version of the example app on Windows results in the following (dev is fine):

```sh
Express server listening at http://localhost:3000/
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:403:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:56)
    at new ModuleJob (node:internal/modules/esm/module_job:67:26)
    at ModuleLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:254:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:235:17)
    at ModuleLoader.import (node:internal/modules/esm/loader:322:23)
```

PR incoming...

### PR DESCRIPTION
**Pull request by wKovacs64**
Fixes #8

### CODE REVIEW

**Comment by kiliman** [comment]
Nice. Thanks for the fix. Yeah, I should be testing on Windows (I have Parallels running on macOS). I promised on Twitter that I'd get this out sooner rather than later.

Anyway, let me know what you think. I've got a couple of enhancements I'll be pushing out this weekend.

**Comment by kiliman** [comment]
Fixed in v0.3.2

**Comment by wKovacs64** [comment]
> Nice. Thanks for the fix. Yeah, I should be testing on Windows (I have Parallels running on macOS). I promised on Twitter that I'd get this out sooner rather than later.
> 
> Anyway, let me know what you think. I've got a couple of enhancements I'll be pushing out this weekend.

Thanks! Pinged you in your showcase thread on the Remix Discord, let me know if you'd prefer discussions/issues here on the repo.

**Comment by kiliman** [comment]
Let's create a new issue for http/2 on Windows and discuss it there.

**Pull request merged**
